definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
  standard__front_page:
    weight: -50
    menu_name: main
    parent: ''
    enabled: true
    expanded: false
  helloworld__default_controller_hello:
    enabled: true
    menu_name: main
    parent: ''
    expanded: false
    weight: 100
_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
